Repository identity-box/identity-box, pull requests merged in 2020-03, with the labels that each got.

#19 Adds support for lerna-changelog
  CONTRIBUTING.md
  lerna.json
  package.json
  workspaces/homepage/package.json
  yarn.lock
Labels: PR: enhancement :heart_eyes_cat:

#20 Extracts Server and StateSerializer to a new package @identity-box/utils
  CONTRIBUTING.md
  jest.config.js
  lerna.json
  package.json
  workspaces/homepage/confluenza.yml
  workspaces/nameservice/index.js
  workspaces/nameservice/package.json
  workspaces/nameservice/src/entry-point/NameService.js
  workspaces/nameservice/tests/entry-point/NameService.test.js
  workspaces/utils/.gitignore
  workspaces/utils/CONFLUENZA.md
  workspaces/utils/README.md
  workspaces/utils/babel.config.js
  workspaces/utils/package.json
  workspaces/utils/source/index.js
  workspaces/utils/source/server/index.js
  workspaces/utils/source/state-serializer/StateSerializer.js
  workspaces/utils/source/state-serializer/index.js
  workspaces/utils/tests/state-serializer/StateSerializer.test.js
  workspaces/utils/tools/build.js
Labels: PR: Refactoring :hammer:

#24 Updates package dependencies
  .gitignore
  package.json
  workspaces/homepage/package.json
  workspaces/hush-hush/package.json
  workspaces/idapp/package.json
  workspaces/idapp/src/views/address-book/AddressBook.js
  workspaces/idservice/package.json
  workspaces/nameservice/package.json
  workspaces/nameservice/src/entry-point/NameService.js
  workspaces/nameservice/src/server/index.js
  workspaces/nameservice/tests/entry-point/NameService.test.js
  workspaces/queuing-service/package.json
  workspaces/telepath/package.json
  yarn.lock
Labels: PR: Project Dependencies :building_construction:

#25 hush-hush: simplifies next.config.js
  now.json
  workspaces/hush-hush/next.config.js
  workspaces/hush-hush/package.json
  yarn.lock
Labels: PR: enhancement :heart_eyes_cat:

#21 Allow IPFS node to run on a different host
  workspaces/idservice/README.md
  workspaces/idservice/src/identity/IdentityProvider.js
  workspaces/nameservice/src/entry-point/NameService.js
  workspaces/nameservice/tests/entry-point/NameService.test.js
Labels: PR: enhancement :heart_eyes_cat:

#22 Allow nameservice to run on a different host
  workspaces/idservice/README.md
  workspaces/idservice/src/services/IPNSPubSub.js
Labels: PR: enhancement :heart_eyes_cat:

#27 Updates project dependencies
  .travis.yml
  jest.config.js
  package.json
  workspaces/homepage/package.json
  workspaces/hush-hush/package.json
  workspaces/hush-hush/setup-tests.js
  workspaces/idapp/package.json
  workspaces/idbox-react-ui/jest.config.js
  workspaces/idbox-react-ui/package.json
  workspaces/idbox-react-ui/setup-tests.js
  workspaces/idservice/package.json
  workspaces/telepath/package.json
  yarn.lock
Labels: PR: Project Dependencies :building_construction:

#28 homepage: fixes custom 404 page
  now.json
Labels: PR: Bug fix :bug:

#30 Updates telepath and queuing service documentation to include some basic info about `service` channels
  workspaces/queuing-service/README.md
  workspaces/telepath/README.md
Labels: PR: Documentation :book:

#31 Adds GitHub Actions NodeJS workflow
  .github/workflows/nodejs.yml
Labels: PR: Continuous Integration :hammer_and_wrench:

#33 ci: enables caching dependencies
  .github/workflows/nodejs.yml
Labels: PR: Continuous Integration :hammer_and_wrench:

#34 ci: removes old travis configuration
  .travis.yml
Labels: PR: Continuous Integration :hammer_and_wrench:

#18 Correct Romanian translation for the subtitles of the FOSDEM video
  workspaces/homepage/src/content/video/IdentityBox-FOSDEM20-ro.vtt
  workspaces/homepage/src/content/video/Video.js
Labels: PR: Documentation :book:

#32 Adds 3rd party service registration
  .gitignore
  workspaces/idservice/ecosystem.config.js
  workspaces/idservice/package.json
  workspaces/idservice/src/entry-point/IdService.js
  workspaces/idservice/src/services/ServiceBroker.js
  workspaces/idservice/src/services/ServiceManager.js
  workspaces/idservice/src/services/ServiceRegistrationService.js
  workspaces/idservice/src/services/ServiceRegistry.js
  workspaces/idservice/src/services/index.js
  workspaces/idservice/tests/services/ServiceBroker.test.js
  workspaces/idservice/tests/services/ServiceManager.test.js
  workspaces/idservice/tests/services/ServiceRegistrationService.test.js
  workspaces/idservice/tests/services/ServiceRegistry.test.js
  workspaces/idservice/tests/telepath/Telepath.test.js
  workspaces/nameservice/src/entry-point/NameService.js
  workspaces/utils/demo-node-ipc/node-ipc-client.js
  workspaces/utils/demo-node-ipc/node-ipc-server.js
  workspaces/utils/package.json
  workspaces/utils/source/index.js
  workspaces/utils/source/services/Service.js
  workspaces/utils/source/services/ServiceProxy.js
  workspaces/utils/source/services/index.js
  workspaces/utils/source/state-serializer/StateSerializer.js
  workspaces/utils/source/test-utils/IPCTestServer.js
  workspaces/utils/source/test-utils/index.js
  workspaces/utils/tests/services/Service.test.js
  workspaces/utils/tests/services/ServiceProxy.test.js
  workspaces/utils/tests/state-serializer/StateSerializer.test.js
  yarn.lock
Labels: PR: New Feature :rocket:
